[project]
name = "pyreact"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "uvicorn[standard]>=0.34.0",
]
